package com.sheetworld.climate;

/**
 * Terrain parameters derived from vanilla's density function system.
 * 
 * These are used for the hard lookup table that determines terrain CATEGORY
 * before climate-based selection picks the specific biome.
 * 
 * VANILLA'S 6 PARAMETERS:
 * - Temperature: We replace with latitude-based
 * - Humidity: We replace with our moisture model
 * - Continentalness: Ocean vs land (WE USE THIS)
 * - Erosion: Mountain vs flat (WE USE THIS)
 * - Weirdness/PV: Peaks vs valleys (WE USE THIS)
 * - Depth: Surface vs cave (not relevant for surface biomes)
 */
public class TerrainParameters {
    
    // ==================== CONTINENTALNESS THRESHOLDS ====================
    // From vanilla wiki - these determine ocean/coast/land
    // 
    // Vanilla's continentalness is generated by density functions and
    // controls both terrain HEIGHT and biome category.
    
    public static final float MUSHROOM_THRESHOLD = -1.05f;      // Rare isolated islands
    public static final float DEEP_OCEAN_THRESHOLD = -0.455f;   // Deep ocean floor
    public static final float OCEAN_THRESHOLD = -0.19f;         // Regular ocean
    public static final float COAST_THRESHOLD = -0.11f;         // Beaches, coastal biomes
    public static final float NEAR_INLAND_THRESHOLD = 0.03f;    // Just past coast
    public static final float MID_INLAND_THRESHOLD = 0.3f;      // Normal inland
    // Beyond MID_INLAND is far inland
    
    // ==================== EROSION LEVELS ====================
    // 7 levels (0-6) from vanilla
    // Lower = more mountainous/rugged, Higher = flatter/eroded
    
    private static final float[] EROSION_BOUNDARIES = {
        -0.78f,    // 0-1 boundary
        -0.375f,   // 1-2 boundary
        -0.2225f,  // 2-3 boundary
        0.05f,     // 3-4 boundary
        0.45f,     // 4-5 boundary
        0.55f      // 5-6 boundary
    };
    
    /**
     * Convert erosion value (-1 to 1) to level (0-6).
     * Lower levels = more mountainous, higher levels = flatter
     */
    public static int getErosionLevel(float erosion) {
        if (erosion < EROSION_BOUNDARIES[0]) return 0;
        if (erosion < EROSION_BOUNDARIES[1]) return 1;
        if (erosion < EROSION_BOUNDARIES[2]) return 2;
        if (erosion < EROSION_BOUNDARIES[3]) return 3;
        if (erosion < EROSION_BOUNDARIES[4]) return 4;
        if (erosion < EROSION_BOUNDARIES[5]) return 5;
        return 6;
    }
    
    // ==================== PEAKS AND VALLEYS ====================
    // Calculated from weirdness using vanilla's formula
    // 
    // PV controls where rivers carve through terrain and where
    // mountain peaks rise up.
    
    /**
     * Calculate PV (peaks and valleys) from weirdness.
     * Vanilla formula: PV = 1 - |3|W| - 2|
     * 
     * Result interpretation:
     * - High positive PV (~0.7 to 1.0) = peaks
     * - Mid positive PV (~0.2 to 0.7) = high terrain / hills
     * - Near zero PV (~-0.2 to 0.2) = mid terrain
     * - Negative PV (~-0.85 to -0.2) = low terrain
     * - Very negative PV (< -0.85) = valleys (rivers)
     */
    public static float calculatePV(float weirdness) {
        return 1.0f - Math.abs(3.0f * Math.abs(weirdness) - 2.0f);
    }
    
    /**
     * PV levels for the lookup table.
     * 
     * PEAKS: Mountain tops, highest terrain
     * HIGH: Hills, elevated terrain
     * MID: Normal terrain, rolling hills
     * LOW: Lower terrain, plains
     * VALLEYS: River valleys, lowest terrain
     */
    public enum PVLevel {
        VALLEYS,   // PV < -0.85 - river valleys, lowest terrain
        LOW,       // PV -0.85 to -0.2 - low terrain
        MID,       // PV -0.2 to 0.2 - mid terrain  
        HIGH,      // PV 0.2 to 0.7 - high terrain / hills
        PEAKS      // PV > 0.7 - mountain peaks
    }
    
    /**
     * Convert PV value to level category.
     */
    public static PVLevel getPVLevel(float pv) {
        if (pv > 0.7f) return PVLevel.PEAKS;
        if (pv > 0.2f) return PVLevel.HIGH;
        if (pv > -0.2f) return PVLevel.MID;
        if (pv > -0.85f) return PVLevel.LOW;
        return PVLevel.VALLEYS;
    }
    
    /**
     * Continentalness categories.
     */
    public enum ContinentalnessLevel {
        MUSHROOM,      // < -1.05 - rare isolated islands
        DEEP_OCEAN,    // -1.05 to -0.455
        OCEAN,         // -0.455 to -0.19
        COAST,         // -0.19 to -0.11
        NEAR_INLAND,   // -0.11 to 0.03
        MID_INLAND,    // 0.03 to 0.3
        FAR_INLAND     // > 0.3
    }
    
    /**
     * Convert continentalness to category.
     */
    public static ContinentalnessLevel getContinentalnessLevel(float continentalness) {
        if (continentalness < MUSHROOM_THRESHOLD) return ContinentalnessLevel.MUSHROOM;
        if (continentalness < DEEP_OCEAN_THRESHOLD) return ContinentalnessLevel.DEEP_OCEAN;
        if (continentalness < OCEAN_THRESHOLD) return ContinentalnessLevel.OCEAN;
        if (continentalness < COAST_THRESHOLD) return ContinentalnessLevel.COAST;
        if (continentalness < NEAR_INLAND_THRESHOLD) return ContinentalnessLevel.NEAR_INLAND;
        if (continentalness < MID_INLAND_THRESHOLD) return ContinentalnessLevel.MID_INLAND;
        return ContinentalnessLevel.FAR_INLAND;
    }
    
    /**
     * Debug string for current terrain parameters.
     */
    public static String getDebugString(float continentalness, float erosion, float weirdness) {
        float pv = calculatePV(weirdness);
        return String.format("C:%s E:%d PV:%s (c=%.2f e=%.2f w=%.2f pv=%.2f)",
            getContinentalnessLevel(continentalness),
            getErosionLevel(erosion),
            getPVLevel(pv),
            continentalness, erosion, weirdness, pv);
    }
}
